### Numpy:-

In [3]:
import numpy as np
import pandas as pd

In [4]:
# numpy-- numerical python
# arrays-- lists

In [6]:
a1 = np.array([12,11,13,14,15])
type(a1)

numpy.ndarray

In [7]:
a1

array([12, 11, 13, 14, 15])

In [8]:
a1.ndim

1

In [9]:
a2 = np.array([[12,11,12,23,34,54]])
a2

array([[12, 11, 12, 23, 34, 54]])

In [10]:
a2.ndim

2

In [11]:
type(a2)

numpy.ndarray

In [12]:
a2 = np.array([
             [1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3 = np.array([
    [
        [1,2],
        [3,4]   
    ],
    [
        [5,6],
        [7,8]
    ]
])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a3.ndim

3

In [15]:
a1

array([12, 11, 13, 14, 15])

In [16]:
a1[:4]

array([12, 11, 13, 14])

In [17]:
arr = np.array([12,13,10,44,32,19])
arr

array([12, 13, 10, 44, 32, 19])

In [18]:
arr.max()

44

In [19]:
arr.min()

10

In [20]:
arr.sum()

130

In [21]:
arr.argmax()

3

In [22]:
arr.argmin()

2

In [23]:
arr1 = np.array([
    [1,2,3],
    [5,4,3],
    [9,8,1]
])
arr1

array([[1, 2, 3],
       [5, 4, 3],
       [9, 8, 1]])

In [24]:
arr2 = np.array([
    [11,2,6],
    [5,4,3],
    [9,8,1]
])
arr2

array([[11,  2,  6],
       [ 5,  4,  3],
       [ 9,  8,  1]])

In [25]:
arr1 + arr2

array([[12,  4,  9],
       [10,  8,  6],
       [18, 16,  2]])

In [26]:
arr1.sum(axis=1)

array([ 6, 12, 18])

In [27]:
arr1.sum(axis=0)

array([15, 14,  7])

In [28]:
n = np.identity(6)

In [29]:
n

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
n.ndim

2

In [31]:
n.reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [32]:
n.reshape(2,18)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1.]])

In [33]:
n.sum()

6.0

In [34]:
n.reshape(-1)

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [35]:
i=np.identity(10)

In [36]:
i.reshape(4,25)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
np.sort(arr)

array([10, 12, 13, 19, 32, 44])