In [1]:
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
data = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=10)

In [3]:
x,y = data

In [4]:
x[0]

array([-1.00583777, -0.37653943, -0.62017967, -0.15756653, -1.12080531,
       -0.58909086, -1.57457766,  1.67804613,  1.0801799 ,  0.35358714])

In [5]:
y[0]

np.int64(0)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [8]:
len(x_train)

750

In [9]:
len(x_test)

250

In [10]:
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [12]:
confusion_matrix(y_pred, y_test)

array([[116,  23],
       [ 19,  92]])

In [13]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       139
           1       0.80      0.83      0.81       111

    accuracy                           0.83       250
   macro avg       0.83      0.83      0.83       250
weighted avg       0.83      0.83      0.83       250



In [14]:
accuracy_score(y_pred, y_test)

0.832

In [15]:
x1,y1 = make_classification(n_samples=10, n_classes=2, n_features=10)

In [16]:
y1_pred = model.predict(x1)

In [17]:
y1

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0])

In [18]:
accuracy_score(y1,y1_pred)

0.5

In [19]:
x1

array([[ 0.11108829, -0.87682782,  1.1370186 ,  0.07255728, -3.16037826,
         1.5297873 , -0.47058648,  0.07392828,  1.37836845,  0.27399399],
       [-0.5333525 ,  1.95296005, -1.21093598,  0.2015967 , -1.31749439,
         0.02361702,  0.05123489, -0.20301393,  1.51326676, -1.29481009],
       [ 0.39970494, -1.20897646,  0.84186132, -0.09944934,  2.56792307,
        -1.25561031, -1.20716998,  1.47956944, -1.03103472,  0.75377423],
       [ 0.16884551,  0.68946801,  0.57953959,  0.34793956, -0.98823722,
         1.67452045, -0.62835684, -0.48733552, -0.59249705, -0.97875163],
       [ 0.31903003, -0.92673282,  1.13972567,  0.05964545, -0.35318474,
        -0.21469916, -1.01604545, -0.34258573, -0.80300326,  0.32170711],
       [-0.26613237, -0.67062373, -0.83887237, -0.41405605,  0.01750118,
        -0.8024759 , -0.04160191, -0.13372169,  0.14864222,  1.09453623],
       [ 0.14076902,  2.08324679,  2.25163012,  1.18887217,  0.25970999,
         1.13804382,  0.82979053,  1.6436437 

In [20]:
x[1]

array([ 0.41117999,  0.76240872, -0.78421   , -0.09647917, -0.40875846,
       -0.66578006,  0.21094182, -0.85044853, -0.46130068,  1.06223729])

In [21]:
x

array([[-1.00583777, -0.37653943, -0.62017967, ...,  1.67804613,
         1.0801799 ,  0.35358714],
       [ 0.41117999,  0.76240872, -0.78421   , ..., -0.85044853,
        -0.46130068,  1.06223729],
       [-1.52540752,  2.22793382,  0.5477266 , ...,  2.44004248,
         1.69891857, -0.70530243],
       ...,
       [-1.614926  ,  0.74310266,  1.13675653, ...,  2.8471565 ,
        -0.91145218, -1.22062837],
       [-0.14262151, -1.43323743, -2.54920034, ...,  0.39777869,
        -0.71639987,  0.6122551 ],
       [-0.1251796 ,  0.73011191, -1.87888552, ...,  0.74154153,
         0.30886522, -1.36966537]], shape=(1000, 10))